# This is a config for E2B sandbox template.
# You can use template ID (42b324z66dxcm9gmhnp7) or template name (vibe-nextjs-test-dev) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-dev") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-dev") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-dev')

team_id = "fdb4c52a-97ec-4678-903b-b41eadfc1fc3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-dev"
template_id = "42b324z66dxcm9gmhnp7"
